-- Typed models for the StarWars SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class Film
---@field characters? table
---@field created? string
---@field director? string
---@field edited? string
---@field episode_id? number
---@field opening_crawl? string
---@field planets? table
---@field producer? string
---@field release_date? string
---@field species? table
---@field starships? table
---@field title? string
---@field url? string
---@field vehicles? table

---@class FilmLoadMatch
---@field id number

---@class FilmListMatch
---@field characters? table
---@field created? string
---@field director? string
---@field edited? string
---@field episode_id? number
---@field opening_crawl? string
---@field planets? table
---@field producer? string
---@field release_date? string
---@field species? table
---@field starships? table
---@field title? string
---@field url? string
---@field vehicles? table

---@class PeopleList

---@class Person
---@field birth_year? string
---@field created? string
---@field edited? string
---@field eye_color? string
---@field films? table
---@field gender? string
---@field hair_color? string
---@field height? string
---@field homeworld? string
---@field mass? string
---@field name? string
---@field skin_color? string
---@field species? table
---@field starships? table
---@field url? string
---@field vehicles? table

---@class PersonLoadMatch
---@field id number

---@class PersonListMatch
---@field birth_year? string
---@field created? string
---@field edited? string
---@field eye_color? string
---@field films? table
---@field gender? string
---@field hair_color? string
---@field height? string
---@field homeworld? string
---@field mass? string
---@field name? string
---@field skin_color? string
---@field species? table
---@field starships? table
---@field url? string
---@field vehicles? table

---@class Planet
---@field climate? string
---@field created? string
---@field diameter? string
---@field edited? string
---@field films? table
---@field gravity? string
---@field name? string
---@field orbital_period? string
---@field population? string
---@field residents? table
---@field rotation_period? string
---@field surface_water? string
---@field terrain? string
---@field url? string

---@class PlanetLoadMatch
---@field id number

---@class PlanetListMatch
---@field climate? string
---@field created? string
---@field diameter? string
---@field edited? string
---@field films? table
---@field gravity? string
---@field name? string
---@field orbital_period? string
---@field population? string
---@field residents? table
---@field rotation_period? string
---@field surface_water? string
---@field terrain? string
---@field url? string

---@class Species
---@field average_height? string
---@field average_lifespan? string
---@field classification? string
---@field created? string
---@field designation? string
---@field edited? string
---@field eye_colors? string
---@field films? table
---@field hair_colors? string
---@field homeworld? string
---@field language? string
---@field name? string
---@field people? table
---@field skin_colors? string
---@field url? string

---@class SpeciesLoadMatch
---@field id number

---@class SpeciesListMatch
---@field average_height? string
---@field average_lifespan? string
---@field classification? string
---@field created? string
---@field designation? string
---@field edited? string
---@field eye_colors? string
---@field films? table
---@field hair_colors? string
---@field homeworld? string
---@field language? string
---@field name? string
---@field people? table
---@field skin_colors? string
---@field url? string

---@class Starship
---@field MGLT? string
---@field cargo_capacity? string
---@field consumables? string
---@field cost_in_credits? string
---@field created? string
---@field crew? string
---@field edited? string
---@field films? table
---@field hyperdrive_rating? string
---@field length? string
---@field manufacturer? string
---@field max_atmosphering_speed? string
---@field model? string
---@field name? string
---@field passengers? string
---@field pilots? table
---@field starship_class? string
---@field url? string

---@class StarshipLoadMatch
---@field id number

---@class StarshipListMatch
---@field MGLT? string
---@field cargo_capacity? string
---@field consumables? string
---@field cost_in_credits? string
---@field created? string
---@field crew? string
---@field edited? string
---@field films? table
---@field hyperdrive_rating? string
---@field length? string
---@field manufacturer? string
---@field max_atmosphering_speed? string
---@field model? string
---@field name? string
---@field passengers? string
---@field pilots? table
---@field starship_class? string
---@field url? string

---@class Vehicle
---@field cargo_capacity? string
---@field consumables? string
---@field cost_in_credits? string
---@field created? string
---@field crew? string
---@field edited? string
---@field films? table
---@field length? string
---@field manufacturer? string
---@field max_atmosphering_speed? string
---@field model? string
---@field name? string
---@field passengers? string
---@field pilots? table
---@field url? string
---@field vehicle_class? string

---@class VehicleLoadMatch
---@field id number

---@class VehicleListMatch
---@field cargo_capacity? string
---@field consumables? string
---@field cost_in_credits? string
---@field created? string
---@field crew? string
---@field edited? string
---@field films? table
---@field length? string
---@field manufacturer? string
---@field max_atmosphering_speed? string
---@field model? string
---@field name? string
---@field passengers? string
---@field pilots? table
---@field url? string
---@field vehicle_class? string

local M = {}

return M
